subject: "Rescue keyword"
description: "exceptions list / without explicit exceptions list"
notes: >
  The rescue branch is represented as a RescueStandardErrorNode node.
focused_on_node: "org.truffleruby.language.exceptions.TryNode"
ruby: |
  begin
    "foo"
  rescue
    42
  end
ast: |
  TryNodeGen
      attributes:
          flags = 0
          sourceCharIndex = 0
          sourceLength = 29
      children:
          rescueParts = [
              RescueStandardErrorNode
                  attributes:
                      canOmitBacktrace = true
                      flags = 0
                      sourceCharIndex = 14
                      sourceLength = 11
                  children:
                      rescueBody =
                          IntegerFixnumLiteralNode
                              attributes:
                                  flags = 1
                                  sourceCharIndex = 23
                                  sourceLength = 2
                                  value = 42
          ]
          tryPart =
              StringLiteralNode
                  attributes:
                      encoding = UTF-8
                      flags = 1
                      sourceCharIndex = 8
                      sourceLength = 5
                      tstring = foo